<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CodeAnalysisVersion>5.9.0</CodeAnalysisVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ICSharpCode.Decompiler" Version="11.1.0.9782" />
    <PackageVersion Include="Krafs.Publicizer" Version="2.3.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.Diagnostics.NETCore.Client" Version="0.2.745401" />
    <PackageVersion Include="Microsoft.Diagnostics.DbgShim" Version="10.0.745401" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(CodeAnalysisVersion)" />
    <PackageVersion Include="Microsoft.DiaSymReader" Version="2.0.0" />
    <!-- Dev dependencies -->
    <PackageVersion Include="NLog" Version="6.2.1" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.15.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <!-- To Remove -->
    <PackageVersion Include="Microsoft.VisualStudio.Shared.VSCodeDebugProtocol" Version="18.0.10427.1" />
  </ItemGroup>
</Project>